### ISSUE TITLE
Any chance of a podspec?

### ISSUE THREAD

**Issue by brenwell** [iluuu1994/ITProgressBar-iOS#1]
Thanks for the lib!

I was wondering if there was any chance of a cocoapod?

**Comment by iluuu1994** [comment]
You're welcome!

Looks like you were not patient enough :P
Feel free to create a pull-request.

**Comment by brenwell** [comment]
Hey,

I would love to create a pull request, though I have actually never done one. 
I forked the project and added a podspec, but it is specific for my fork of the repo.

Should I adjust it to your repo and the submit a pull request?
Or shall I just paste the podspec here?

Thanks man

**Comment by iluuu1994** [comment]
However you want. Btw you can also create a branch of your fork and submit that as a pull request so you don't mess with your master branch.

**Comment by brenwell** [comment]
oh good to know, I will give that a go. Doing a pull-request seems like something useful to learn.

**Comment by iluuu1994** [comment]
Cool :)
Thanks man!

**Comment by iluuu1994** [comment]
#2

**Comment by brenwell** [comment]
Thanks man, all the best

**Comment by iluuu1994** [comment]
Likewise!
