### ISSUE TITLE
animation for increate/decrease width not working.

### ISSUE THREAD

**Issue by fukemy** [iluuu1994/ITProgressBar-iOS#3]
Hello. Thanks for great lib
I used 
    _progress.progress = [taskDetail.Progress intValue];
But it change to progress immediately, no animation trigged :(. Plz help

**Comment by iluuu1994** [comment]
Sorry for the late response. The code above should work just fine.

Have you figured out why this wasn't working?

**Comment by fukemy** [comment]
Hello. I found the animation work but my simulator sometimes didnt show with animate ( dont know why?) .

**Comment by iluuu1994** [comment]
Ok, thanks for letting me know
